from flask import Flask, render_template, redirect, url_for, request
from flask_mail import Mail
from models import db, login_manager
from routes.auth import auth_bp
from routes.dashboard import dashboard_bp
from routes.payments import payments_bp, PLANS_CONFIG
from routes.content import content_bp 
from routes.sites import sites_bp 
from routes.radar import radar_bp
from routes.admin import admin_bp
from flask_login import login_required, current_user
import os
from dotenv import load_dotenv # Adicionado

# Carrega o .env explicitamente
load_dotenv()
print("--- DEBUG DE CONEXÃO ---")
print(f"DATABASE_URL carregada: {os.environ.get('DATABASE_URL')[:20]}...") 
print("------------------------")

app = Flask(__name__)

# Configurações básicas
app.config['SECRET_KEY'] = os.environ.get('FLASK_SECRET_KEY', 'chave-padrao-segura')

# Configuração do Banco de Dados (FORÇANDO POSTGRES)
database_url = os.environ.get('DATABASE_URL')

if database_url and database_url.startswith("postgres://"):
    database_url = database_url.replace("postgres://", "postgresql://", 1)

# Se não houver database_url, o app deve avisar em vez de criar um sqlite silencioso
if not database_url:
    raise ValueError("ERRO: Variável DATABASE_URL não encontrada no arquivo .env!")

app.config['SQLALCHEMY_DATABASE_URI'] = database_url
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db.init_app(app)
login_manager.init_app(app)
login_manager.login_view = 'auth.login'

# Registro de Blueprints
app.register_blueprint(auth_bp)
app.register_blueprint(dashboard_bp)
app.register_blueprint(sites_bp, url_prefix='/sites')
app.register_blueprint(radar_bp, url_prefix='/radar')
app.register_blueprint(content_bp, url_prefix='/content')
app.register_blueprint(payments_bp, url_prefix='/billing')
app.register_blueprint(admin_bp, url_prefix='/admin')

@app.route('/')
def index():
    # Captura o idioma da URL (ex: ?lang=en). O padrão é 'pt'
    lang = request.args.get('lang', 'pt')
    
    # Dicionário de traduções simples
    translations = {
        'pt': {
            'hero_title': 'Blogs que rendem',
            'hero_subtitle': 'em piloto automático',
            'hero_line': 'Sua produção de conteúdo escalada por Inteligência Artificial de elite.',
            'hero_button': 'Teste Grátis',
        },
        'en': {
            'hero_title': 'Blogs that earn ',
            'hero_subtitle': 'on autopilot',
            'hero_line': 'Your content generated by best AI ever',
            'hero_button': 'Free Test',
        }
    }
    
    # Pega os textos do idioma selecionado
    texts = translations.get(lang, translations['pt'])
    
    return render_template('landing.html', 
                           planos=PLANS_CONFIG, 
                           t=texts, 
                           current_lang=lang)

@app.route('/dashboard-hub')
@login_required
def dashboard_hub():
    status = current_user.get_setup_status()
    finished = request.args.get('finished') == 'true'
    if status == 'complete' and not finished:
        return redirect(url_for('dashboard.dashboard_view'))
    return render_template('onboarding.html', status=status)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)